export default{
    path:'/weeat',
    name:"weeat",
    component:()=>import('@/views/Weeat/Weeat.vue'),
    children:[
        {
            path:'food',
            component:()=>import('@/views/Weeat/Food/Food.vue'),
            children:[
                {
                    path:'recommend',
                    component:()=>import('@/views/Weeat/Food/Recommend.vue'),
                },
                {
                    path:'truetake',
                    component:()=>import('@/views/Weeat/Food/Truetake.vue'),                     
                },
            ]
        },
        {
            path:'game',
            component:()=>import('@/views/Weeat/Game/Game.vue')
        },
        {
            path:'/weeat',
            redirect:'/weeat/food'
        },
        {
            path:'selectfood/:foodname/:id',
            component:()=>import('@/views/Weeat/Truetake/Selectfood.vue')
        }
    ]
}