export default{
    path:'/my',
    component:()=>import("@/views/My/My.vue"),
    children:[ 
        {
            path:'center',
            component:()=>import('@/views/My/Center.vue')
        },
        {
            path:'login',
            component:()=>import('@/components/Login.vue')
        },
        {
            path:'register',
            component:()=>import('@/components/Register.vue')
        },
        {
            path:'findpassword',
            component:()=>import('@/components/FindPassword.vue')
        },
        {
            path:'mymenu',
            component:()=>import('@/views/My/Mymenu.vue')
        },
        {
            path:'/my',
            redirect:'/my/center'
        } 
    ]
}